module.exports={    
    COLORS: {
        I: 'cyan',
        J: 'blue',
        L: 'orange',
        O: 'yellow',
        S: 'green',
        T: 'purple',
        Z: 'red'
    },
    SHAPES: {
        I: [[0, 0, 0, 0],
            [1, 1, 1, 1],
            [0, 0, 0, 0],
            [0, 0, 0, 0]],
        J: [[2, 0, 0],
            [2, 2, 2],
            [0, 0, 0]],
        L: [[0, 0, 3],
            [3, 3, 3],
            [0, 0, 0]],
        O: [[4, 4],
            [4, 4]],
        S: [[0, 5, 5],
            [5, 5, 0],
            [0, 0, 0]],
        T: [[0, 6, 0],
            [6, 6, 6],
            [0, 0, 0]],
        Z: [[7, 7, 0],
            [0, 7, 7],
            [0, 0, 0]]            
    },
    GRID_ROWS: 20,
    GRID_COLS: 10,
    Y_START: -1,
    X_START: 3,
    HARD_DROP: 60,
    DEFAULT_YSPEED: 8
}